### ISSUE TITLE
Doc etc nits

### ISSUE THREAD

**Issue by mohawk2** [nrdvana/perl-Math-3Space#2]
~::Vector->new is documented to take `(x=>$x, ...)` but doesn't~.

If I delete `_init` everything still works, so it's unused.

**Comment by mohawk2** [comment]
The `dot` method bizarrely normalises the dot product by dividing it by the product of the lengths of the two vectors. I believe you'll find this is actually the vector cosine: https://en.wikipedia.org/wiki/Cosine_similarity

**Comment by nrdvana** [comment]
True about the dot product.  That evolved from older code always using unit vectors, and the cosine being synonymous with the dot product, then I relaxed the constraints to allow scaling (requiring the normalization) but didn't rename the function.

**Comment by nrdvana** [comment]
The _init method is waiting for a full implementation of `Math::3Space->new()`, which will call _init.  I didn't get around to fully specifying the constructor yet, since the `space()` exported function works well enough for now.

**Comment by mohawk2** [comment]
Oh no, now I need to adjust/rebase my branch! Thank you. By the way, this is my implementation of a PDL version of the module, as alluded to in https://www.perlmonks.org/?node_id=11157584

I'm thinking I'll make a PR for that, which will then probably want some kind of "recommends" of PDL adding. Is that a thing you're interested in merging/supporting? If so, then someone would need to generalise most of the tests so they can be called either for the XS or the PDL implementations? Currently I've just copied tests 2-5 to a `*-pdl.t` version.

**Comment by nrdvana** [comment]
I think it's more useful to have an interoperable data format than my own custom vector back-end, but at the same time fewer dependencies are nice and `pack('F3',...` is a nice simple format.  I'll wait and see how it looks to make it an optional dependency.  Benchmarks will also be interesting.

**Comment by mohawk2** [comment]
I'd be extremely interested in benchmarks. Clearly your code made a lot of effort to be highly efficient, but to scale over many data points looping would need to be done in Perl, which will impose its own performance costs.

Meanwhile in PDL land, I've made some (possibly imperfect as not tried it yet) effort to make the code work when broadcasting over many data points; even operations that inherently return one data point, eg `dot`, return an ndarray so they would still broadcast.

I don't know what an interoperable data format would look like? PDL can easily deal with various data formats including STL, and using a `pack`ed SV is trivial (and I ported that bit of code too, it's 2 lines).

**Comment by mohawk2** [comment]
Also, and while it's not too late to change it: how open are you to changing the direction of rotation? I believe it's currently positive=clockwise, whereas in the normal way of things it's positive=anti-clockwise?

**Comment by nrdvana** [comment]
> I believe it's currently positive=clockwise, whereas in the normal way of things it's positive=anti-clockwise?

Can you give an example?  Using one of the unit tests,
```
	# quarter rotation around Z axis should leave XV pointing at Y and YV pointing at -X
	is( space->rot_z(.25), object {
		call is_normal => T;
		call xv => vec_check(0,1,0);
		call yv => vec_check(-1,0,0);
		call zv => vec_check(0,0,1);
	}, 'rotate around parent Z axis' );
```
and the right-hand rule, if the thumb (Z) is pointing at your face, the quarter rotation is anti-clockwise from straight fingers toward bent fingers.

_(disclaimer, I'm left-handed and dyslexic)_

**Comment by mohawk2** [comment]
> > I believe it's currently positive=clockwise, whereas in the normal way of things it's positive=anti-clockwise?
> 
> Can you give an example? Using one of the unit tests,
> 
> ```
> 	# quarter rotation around Z axis should leave XV pointing at Y and YV pointing at -X
> 	is( space->rot_z(.25), object {
> 		call is_normal => T;
> 		call xv => vec_check(0,1,0);
> 		call yv => vec_check(-1,0,0);
> 		call zv => vec_check(0,0,1);
> 	}, 'rotate around parent Z axis' );
> ```
> 
> and the right-hand rule, if the thumb (Z) is pointing at your face, the quarter rotation is anti-clockwise from straight fingers toward bent fingers.
> 
> _(disclaimer, I'm left-handed and dyslexic)_

I'm pleased that I'm wrong! Thank you for checking this and sorry for my confusion.
